import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/context/AuthProvider'
import ToasterProvider from '@/context/ToasterProvider'
import ActiveStatus from './components/ActiveStatus'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Messanger Clone',
  description: 'Generated by showkatul islam',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
         <ToasterProvider/>
         <ActiveStatus/>
         {children}
        </AuthProvider>
      </body>
    </html>
  )
}
